[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "hawk poem soon gorilla powder bulk fox limit asset couch define burst tornado cruise east view pottery bounce twice real nut mom joke inform"
